query SourceWidget{
  user {
    id
    dataSources {
      id
      name
      paused
      createdAt
      updatedAt
      lastSyncedAt
      lastSuccessfulAt
      lastSuccessfulRuntime
      lastResult
      lastFailedAt
      lastFailedRuntime
      lastAttemptedAt
      lastError
      source
      config
    }
  }
}
